---
- hosts: mywebservers
  become: yes
  tasks:
    - name: i want to install webserver on ubuntu
      apt:
        name: "{{mywebpackonubuntu}}"
        state: present
      when: ansible_os_family == "Debian"
    
    - name: i want to start webserver
      service:
        name: "{{mywebpackonubuntu}}"
        state: started
      when: ansible_os_family == "Debian"

    - name: i want to install webserver on redhat
      apt:
        name: "{{mywebpackonredhat}}"
        state: present
      when: ansible_os_family == "Redhat"

    - name: i want to install webserver
      service:
        name: apache2
        state: started
      when: ansible_os_family == "Redhat"     
      